name: build-android-apk

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps (full toolchain)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            autoconf automake libtool pkg-config \
            cmake gettext \
            zip unzip rsync patch \
            openjdk-17-jdk \
            python3-pip python3-setuptools \
            libsdl2-dev libffi-dev libssl-dev zlib1g-dev liblzma-dev \
            libjpeg-dev libfreetype6-dev libpng-dev \
            libncurses5 libncurses5-dev libtinfo5

      - name: Upgrade pip & install buildozer
        run: |
          python -m pip install --upgrade pip
          pip install "cython==0.29.36" buildozer

      - name: Build APK (debug)
        run: |
          buildozer android debug
        env:
          BUILDOZER_WARN_ON_ROOT: "0"
