name: build-android-apk

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip openjdk-17-jdk python3-pip \
            libsdl2-dev libffi-dev libssl-dev liblzma-dev zlib1g-dev \
            libjpeg-dev libfreetype6-dev

      - name: Install buildozer & deps
        run: |
          python -m pip install --upgrade pip
          pip install "cython==0.29.36" buildozer

      - name: Build APK (debug)
        run: |
          buildozer android debug
        env:
          BUILDOZER_WARN_ON_ROOT: "0"
